services:
  web:
    build: ./web
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_volume:
